apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: recipe_box
deploy:
  kustomize:
    paths:
     - kubernetes/overlays/dev
profiles:
  - name: staging
    deploy:
      kustomize:
        paths:
         - kubernetes/overlays/staging
