apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: recipe-box
    component: web
spec:
  ports:
  - port: 9101
    targetPort: 9101
  selector:
    app: recipe-box
    component: web
