spring:
  datasource:
    url: jdbc:hsqldb:mem:bdbi_basis_datamart_dev;DB_CLOSE_DELAY=1
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database: HSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
