apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: shouter
    component: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: shouter
    component: redis